# Keep dependencies up to date: a pull request once a month, tested by CI before merging.
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      dependencies:
        patterns: ["*"]
    open-pull-requests-limit: 3
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
